# Generated by Django 5.2.2 on 2025-06-16 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ROUBO', 'Roubo'), ('FURTO', 'Furto'), ('OUTRO', 'Outro')], max_length=5, verbose_name='Tipo de Crime')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Ocorrido')),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização (clique no mapa)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço Aproximado')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Registro de Crime',
                'verbose_name_plural': 'Registros de Crimes',
                'ordering': ['-data'],
            },
        ),
    ]
