# Generated by Django 5.2.3 on 2025-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='tipo',
            field=models.CharField(choices=[('ROUBO', 'Roubo'), ('FURTO', 'Furto'), ('HOMICIDIO', 'Homicidio'), ('OUTRO', 'Outro')], max_length=25, verbose_name='Tipo de Crime'),
        ),
    ]
