# Generated by Django 5.2.3 on 2025-06-25 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto_grad', models.CharField(choices=[('Gen', 'General'), ('Cel', 'Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1º Ten', 'Primeiro Tenente'), ('2º Ten', 'Segundo Tenente'), ('Asp', 'Aspirante'), ('S Ten', 'Subtenente'), ('1º Sgt', 'Primeiro Sargento'), ('2º Sgt', 'Segundo Sargento'), ('3º Sgt', 'Terceiro Sargento'), ('Cb', 'Cabo'), ('Sd', 'Soldado')], max_length=10, verbose_name='Posto/Graduação')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('qra', models.CharField(help_text='Identificação única do militar', max_length=20, unique=True, verbose_name='QRA')),
                ('rgpm', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='RGPM')),
                ('validade_rgpm', models.DateField(blank=True, null=True, verbose_name='Validade RGPM')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH')),
                ('validade_cnh', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('unidade', models.CharField(max_length=50, verbose_name='Unidade')),
                ('sub_lotacao_funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Lotação/Função')),
                ('situacao_atual', models.CharField(choices=[('Ativo', 'Ativo'), ('Licenciado', 'Licenciado'), ('Transferido', 'Transferido'), ('Afastado', 'Afastado'), ('Outro', 'Outro')], default='Ativo', max_length=20, verbose_name='Situação Atual')),
                ('detalhes_situacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Detalhes da Situação')),
            ],
            options={
                'verbose_name': 'Militar',
                'verbose_name_plural': 'Militares',
                'ordering': ['posto_grad', 'nome'],
            },
        ),
    ]
