# Generated by Django 5.2.3 on 2025-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (DDD) 99999-9999', max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='militar',
            name='posto_grad',
            field=models.CharField(choices=[('Cel', 'Coronel'), ('Ten Cel', 'Tenente Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1º Ten', 'Primeiro Tenente'), ('2º Ten', 'Segundo Tenente'), ('Asp', 'Aspirante'), ('Sub Ten', 'Subtenente'), ('1º Sgt', 'Primeiro Sargento'), ('2º Sgt', 'Segundo Sargento'), ('3º Sgt', 'Terceiro Sargento'), ('Cb', 'Cabo'), ('Sd', 'Soldado')], max_length=20, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='militar',
            name='situacao_atual',
            field=models.CharField(choices=[('Pronto Emprego', 'Pronto Emprego'), ('Agregado', 'Agregado'), ('Em Curso', 'Em Curso'), ('Afastado/Licença', 'Afastado/Licença'), ('Impedido Operacional', 'Impedido Operacional')], default='Ativo', max_length=20, verbose_name='Situação Atual'),
        ),
        migrations.AlterField(
            model_name='militar',
            name='unidade',
            field=models.CharField(choices=[('5º BPM', '5º BPM')], max_length=20, verbose_name='unidade'),
        ),
    ]
