# Generated by Django 5.2.2 on 2025-06-10 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
    ]
