# Generated by Django 5.2.2 on 2025-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela', '0002_noticia_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/fotos/', verbose_name='Foto (opcional)'),
        ),
    ]
